.TH git-clone-org 1 "01 Feb 2021" "1.0"
.SH NAME
git-clone-org - clone many repositories in a Github organization
.SH SYNOPSIS
git clone-org -o ORG [-t TOPIC] [-p PATH] [-y]
.SH DEPENDENCIES
jq, Github cli
.SH OPTIONS
.TP
-o, --org ORG
Github organization. Required if the GITHUB_ORG environment variable is not set.
.TP
-y, --yes
Clone without prompting for confirmation.
.TP
-p, --path PATH
Clone path. Default: current directory.
.TP
-t, --topic TOPIC
Clone repositories with this topic
.SH EXAMPLES
.TP
git clone-org -o my-github-org
Clone all repositories in "my-github-org" to the current directory.
.TP
git clone-org -o my-github-org -t my-topic
Clone all repositories in "my-github-org" that have topic "my-topic" to the current directory.
.TP
git clone-org -o my-github-org -p ~/git/my-org
Clone all repositories in "my-github-org" to "~/git/my-org".
